apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-load-balancer
  template:
    metadata:
      labels:
        app: custom-load-balancer
    spec:
      containers:
      - name: custom-load-balancer
        image: localhost:5001/clb-app:2
        env:
        - name: POD_IPS
          value: "10.244.0.5,10.244.0.6,10.244.0.7"  # Replace with actual pod IPs