apiVersion: v1
kind: Service
metadata:
  name: custom-load-balancer-service
spec:
  type: NodePort
  selector:
    app: custom-load-balancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Replace with an available port